name: Build LaTeX document
on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full biber vim libfontconfig1 

    - name: Compile LaTeX document
      run: |
        latexmk -pdf db.tex

    - name: Commit PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./db.pdf
        git commit -m "Add built PDF" && git push
